apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: d
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: lb-1690475489.ap-south-1.elb.amazonaws.com  # Replace with your Load Balancer's DNS name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tomcat-deploy-project-svc
                port:
                  number: 80
