apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-deploy-project-ingress
  namespace: d
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tomcat-deploy-project-svc
                port:
                  number: 8080
