apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP  # Change this to ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.clusterIPPort }}
      targetPort: {{ .Values.image.containerPort }}
