deployment:
  name: tomcat-deploy-project
  replicaCount: 1
image:
  repository: 654654623396.dkr.ecr.ap-south-1.amazonaws.com/jenkins-docker
  tag: latest
  containerPort: 8080
service:
  type: NodePort
  clusterIPPort: 8080
  nodePort: 30800
namespace: devvv
